version: '2.4'

services:
  team-tigers:
    image: robocupssl/ubuntu-vnc-java:0.3.2
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-tigers-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robocinunification:
    image: robocin/ssl-unification-robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robocinunification-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

team-robocinunificationb:
    image: robocin/ssl-unification-robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robocinunificationb-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robofei:
    image: bollos00/robofeissl-ssl-strategy:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robofei-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robocincoach:
    image: lhcs/robocin-coach:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robocincoach-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

volumes:
  team-tigers-data:
  team-robocinunification-data:
  team-robocinunificationb-data:
  team-robocincoach-data:
  team-robofei-data:

networks:
  match:
  guacamole:
